namespace Hearthstone_Deck_Tracker.Enums
{
	public enum PlayType
	{
		PlayerPlay,
		PlayerDraw,
		PlayerGet,
		PlayerMulligan,
		PlayerHandDiscard,
		PlayerDeckDiscard,
		PlayerBackToHand,
		PlayerSecretPlayed,
		PlayerHeroPower,
		PlayerPlayToDeck,
		PlayerGetToDeck,
		OpponentPlay,
		OpponentDraw,
		OpponentGet,
		OpponentMulligan,
		OpponentHandDiscard,
		OpponentDeckDiscard,
		OpponentPlayToDeck,
		OpponentBackToHand,
		OpponentSecretPlayed,
		OpponentSecretTriggered,
		OpponentHeroPower,
		OpponentGetToDeck
	}
}
