//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearthstone_Deck_Tracker.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hearthstone_Deck_Tracker.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASS ONLY.
        /// </summary>
        internal static string CLASSONLY {
            get {
                return ResourceManager.GetString("CLASSONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        internal static string COST {
            get {
                return ResourceManager.GetString("COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER.
        /// </summary>
        internal static string FILTER {
            get {
                return ResourceManager.GetString("FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO DECK SELECTION.
        /// </summary>
        internal static string MainWindow_AUTODECKSELECTION {
            get {
                return ResourceManager.GetString("MainWindow_AUTODECKSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY IDS TO _CLIPBOARD.
        /// </summary>
        internal static string MainWindow_COPYIDSTOCLIPBOARD {
            get {
                return ResourceManager.GetString("MainWindow_COPYIDSTOCLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DECK.
        /// </summary>
        internal static string MainWindow_DECK {
            get {
                return ResourceManager.GetString("MainWindow_DECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DRUID.
        /// </summary>
        internal static string MainWindow_DRUID {
            get {
                return ResourceManager.GetString("MainWindow_DRUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _EDIT.
        /// </summary>
        internal static string MainWindow_EDIT {
            get {
                return ResourceManager.GetString("MainWindow_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLONE.
        /// </summary>
        internal static string MainWindow_EDITCLONE {
            get {
                return ResourceManager.GetString("MainWindow_EDITCLONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DECK.
        /// </summary>
        internal static string MainWindow_EDITDECK {
            get {
                return ResourceManager.GetString("MainWindow_EDITDECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string MainWindow_EDITDELETE {
            get {
                return ResourceManager.GetString("MainWindow_EDITDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NOTES.
        /// </summary>
        internal static string MainWindow_EDITNOTES {
            get {
                return ResourceManager.GetString("MainWindow_EDITNOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TAGS.
        /// </summary>
        internal static string MainWindow_EDITTAGS {
            get {
                return ResourceManager.GetString("MainWindow_EDITTAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _EXPORT.
        /// </summary>
        internal static string MainWindow_EXPORT {
            get {
                return ResourceManager.GetString("MainWindow_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM _FILE.
        /// </summary>
        internal static string MainWindow_FROMFILE {
            get {
                return ResourceManager.GetString("MainWindow_FROMFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM _ID STRING.
        /// </summary>
        internal static string MainWindow_FROMIDSTRING {
            get {
                return ResourceManager.GetString("MainWindow_FROMIDSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM LAST _GAME.
        /// </summary>
        internal static string MainWindow_FROMLASTGAME {
            get {
                return ResourceManager.GetString("MainWindow_FROMLASTGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM _WEB.
        /// </summary>
        internal static string MainWindow_FROMWEB {
            get {
                return ResourceManager.GetString("MainWindow_FROMWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _HUNTER.
        /// </summary>
        internal static string MainWindow_HUNTER {
            get {
                return ResourceManager.GetString("MainWindow_HUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _IMPORT.
        /// </summary>
        internal static string MainWindow_IMPORT {
            get {
                return ResourceManager.GetString("MainWindow_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MAGE.
        /// </summary>
        internal static string MainWindow_MAGE {
            get {
                return ResourceManager.GetString("MainWindow_MAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NEW.
        /// </summary>
        internal static string MainWindow_NEW {
            get {
                return ResourceManager.GetString("MainWindow_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PALADIN.
        /// </summary>
        internal static string MainWindow_PALADIN {
            get {
                return ResourceManager.GetString("MainWindow_PALADIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PRIEST.
        /// </summary>
        internal static string MainWindow_PRIEST {
            get {
                return ResourceManager.GetString("MainWindow_PRIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ROGUE.
        /// </summary>
        internal static string MainWindow_ROGUE {
            get {
                return ResourceManager.GetString("MainWindow_ROGUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE AS _XML.
        /// </summary>
        internal static string MainWindow_SAVEASXML {
            get {
                return ResourceManager.GetString("MainWindow_SAVEASXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SCREENSHOT.
        /// </summary>
        internal static string MainWindow_SCREENSHOT {
            get {
                return ResourceManager.GetString("MainWindow_SCREENSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SHAMAN.
        /// </summary>
        internal static string MainWindow_SHAMAN {
            get {
                return ResourceManager.GetString("MainWindow_SHAMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SORT / FILTER.
        /// </summary>
        internal static string MainWindow_SORTFILTER {
            get {
                return ResourceManager.GetString("MainWindow_SORTFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _STATS.
        /// </summary>
        internal static string MainWindow_STATS {
            get {
                return ResourceManager.GetString("MainWindow_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearthstone Deck Tracker.
        /// </summary>
        internal static string MainWindow_TITLE {
            get {
                return ResourceManager.GetString("MainWindow_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO _HEARTHSTON.
        /// </summary>
        internal static string MainWindow_TOHEARTHSTONE {
            get {
                return ResourceManager.GetString("MainWindow_TOHEARTHSTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO HEARTHSTONE FROM _WEB.
        /// </summary>
        internal static string MainWindow_TOHEARTHSTONEFROMWEB {
            get {
                return ResourceManager.GetString("MainWindow_TOHEARTHSTONEFROMWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE _NO DECK.
        /// </summary>
        internal static string MainWindow_USENODECK {
            get {
                return ResourceManager.GetString("MainWindow_USENODECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WARLOCK.
        /// </summary>
        internal static string MainWindow_WARLOCK {
            get {
                return ResourceManager.GetString("MainWindow_WARLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WARRIOR.
        /// </summary>
        internal static string MainWindow_WARRIOR {
            get {
                return ResourceManager.GetString("MainWindow_WARRIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANA.
        /// </summary>
        internal static string MANA {
            get {
                return ResourceManager.GetString("MANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        internal static string NAMEALREADYEXISTS {
            get {
                return ResourceManager.GetString("NAMEALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEUTRAL ONLY.
        /// </summary>
        internal static string NEUTRALONLY {
            get {
                return ResourceManager.GetString("NEUTRALONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
    }
}
