name: Bug Report
description: File a bug report
labels:
  - bug
body:
  - type: textarea
    id: expected-behaviour
    attributes:
        label: Expected Behavior
        description: What did you expect to happen?
    validations:
        required: true
  - type: textarea
    id: actual-behaviour
    attributes:
        label: Actual Behavior
        description: What did actually happen?
    validations:
        required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
        label: Steps to reproduce behavior
        description: Can you reproduce it? How?
  - type: textarea
    id: files
    attributes:
        label: Log/Screenshots
        description: If applicable, provide a log of the session where the problem occurred.
    validations:
        required: false
