//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearthstone_Deck_Tracker.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hearthstone_Deck_Tracker.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Druid.
        /// </summary>
        public static string MainWindow_Menu_Class_Druid
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Druid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Hunter.
        /// </summary>
        public static string MainWindow_Menu_Class_Hunter
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Hunter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Mage.
        /// </summary>
        public static string MainWindow_Menu_Class_Mage
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Mage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to P_aladin.
        /// </summary>
        public static string MainWindow_Menu_Class_Paladin
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Paladin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Priest.
        /// </summary>
        public static string MainWindow_Menu_Class_Priest
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Priest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Rogue.
        /// </summary>
        public static string MainWindow_Menu_Class_Rogue
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Rogue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Shaman.
        /// </summary>
        public static string MainWindow_Menu_Class_Shaman
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Shaman", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Warlock.
        /// </summary>
        public static string MainWindow_Menu_Class_Warlock
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Warlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wa_rrior.
        /// </summary>
        public static string MainWindow_Menu_Class_Warrior
        {
            get
            {
                return ResourceManager.GetString("Menu_Class_Warrior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        public static string MainWindow_Menu_Deck
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Archive.
        /// </summary>
        public static string MainWindow_Menu_Deck_Archive
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_Archive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string MainWindow_Menu_Deck_Clone
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_Clone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entire deck.
        /// </summary>
        public static string MainWindow_Menu_Deck_Clone_EntireDeck
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_Clone_EntireDeck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected version.
        /// </summary>
        public static string MainWindow_Menu_Deck_Clone_Version
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_Clone_Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string MainWindow_Menu_Deck_DeleteDeck
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_DeleteDeck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit _deck.
        /// </summary>
        public static string MainWindow_Menu_Deck_EditDeck
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_EditDeck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit na_me.
        /// </summary>
        public static string MainWindow_Menu_Deck_EditName
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_EditName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit _notes.
        /// </summary>
        public static string MainWindow_Menu_Deck_EditNotes
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_EditNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit _tags.
        /// </summary>
        public static string MainWindow_Menu_Deck_EditTags
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_EditTags", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show _missing cards.
        /// </summary>
        public static string MainWindow_Menu_Deck_MissingCards
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_MissingCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to arena.
        /// </summary>
        public static string MainWindow_Menu_Deck_MoveToArena
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_MoveToArena", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move to constructed.
        /// </summary>
        public static string MainWindow_Menu_Deck_MoveToContrstucted
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_MoveToContrstucted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open HearthStats.
        /// </summary>
        public static string MainWindow_Menu_Deck_OpenHearthStats
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_OpenHearthStats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open _website.
        /// </summary>
        public static string MainWindow_Menu_Deck_OpenWebsite
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_OpenWebsite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Quick set tag.
        /// </summary>
        public static string MainWindow_Menu_Deck_QuickSetTag
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_QuickSetTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unarchive.
        /// </summary>
        public static string MainWindow_Menu_Deck_Unarchive
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_Unarchive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Update (web).
        /// </summary>
        public static string MainWindow_Menu_Deck_UpdateWeb
        {
            get
            {
                return ResourceManager.GetString("Menu_Deck_UpdateWeb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E_xport.
        /// </summary>
        public static string MainWindow_Menu_Export
        {
            get
            {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy _names to clipboard.
        /// </summary>
        public static string MainWindow_Menu_Export_Clpiboard
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Clpiboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To _Hearthstone.
        /// </summary>
        public static string MainWindow_Menu_Export_Hearthstone
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Hearthstone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To Hearthstone from _Web.
        /// </summary>
        public static string MainWindow_Menu_Export_Hearthstone_FromWeb
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Hearthstone_FromWeb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy IDs to _clipboard.
        /// </summary>
        public static string MainWindow_Menu_Export_Ids
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Ids", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Screenshot.
        /// </summary>
        public static string MainWindow_Menu_Export_Screenshot
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Screenshot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screenshot (with info).
        /// </summary>
        public static string MainWindow_Menu_Export_Screenshot_Info
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Screenshot_Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as _Xml.
        /// </summary>
        public static string MainWindow_Menu_Export_Xml
        {
            get
            {
                return ResourceManager.GetString("Menu_Export_Xml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_Dashboard
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_DeleteDecks
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_DeleteDecks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_DeleteGames
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_DeleteGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_DeleteSelected
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_DeleteSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_ForceSync
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_ForceSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_Login
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_Logout
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_Sync
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_Sync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_SyncInBackground
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_SyncInBackground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_SyncOnStart
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_SyncOnStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_UploadDecks
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_UploadDecks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_HearthStats_UploadGames
        {
            get
            {
                return ResourceManager.GetString("Menu_HearthStats_UploadGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string MainWindow_Menu_Import
        {
            get
            {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From _Arena.
        /// </summary>
        public static string MainWindow_Menu_Import_Arena
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Arena", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From _Tavern Brawl.
        /// </summary>
        public static string MainWindow_Menu_Import_Brawl
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Brawl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From _Constructed.
        /// </summary>
        public static string MainWindow_Menu_Import_Constructed
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Constructed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string MainWindow_Menu_Import_Other
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From clipboard.
        /// </summary>
        public static string MainWindow_Menu_Import_Other_Clipboard
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Other_Clipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From file.
        /// </summary>
        public static string MainWindow_Menu_Import_Other_File
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Other_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From ids.
        /// </summary>
        public static string MainWindow_Menu_Import_Other_Ids
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Other_Ids", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From last game.
        /// </summary>
        public static string MainWindow_Menu_Import_Other_LastGame
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Other_LastGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From _web.
        /// </summary>
        public static string MainWindow_Menu_Import_Web
        {
            get
            {
                return ResourceManager.GetString("Menu_Import_Web", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MainWindow_Menu_New
        {
            get
            {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_Plugins
        {
            get
            {
                return ResourceManager.GetString("Menu_Plugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_Plugins_Empty
        {
            get
            {
                return ResourceManager.GetString("Menu_Plugins_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Replays.
        /// </summary>
        public static string MainWindow_Menu_Replays
        {
            get
            {
                return ResourceManager.GetString("Menu_Replays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_Replays_ClaimAccount
        {
            get
            {
                return ResourceManager.GetString("Menu_Replays_ClaimAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load from _file.
        /// </summary>
        public static string MainWindow_Menu_Replays_File
        {
            get
            {
                return ResourceManager.GetString("Menu_Replays_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Latest replays.
        /// </summary>
        public static string MainWindow_Menu_Replays_Latest
        {
            get
            {
                return ResourceManager.GetString("Menu_Replays_Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_Menu_Replays_MyAccount
        {
            get
            {
                return ResourceManager.GetString("Menu_Replays_MyAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Select from stats.
        /// </summary>
        public static string MainWindow_Menu_Replays_Stats
        {
            get
            {
                return ResourceManager.GetString("Menu_Replays_Stats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Stats.
        /// </summary>
        public static string MainWindow_Menu_Stats
        {
            get
            {
                return ResourceManager.GetString("Menu_Stats", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Arena.
        /// </summary>
        public static string MainWindow_Menu_Stats_Arena
        {
            get
            {
                return ResourceManager.GetString("Menu_Stats_Arena", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Constructed.
        /// </summary>
        public static string MainWindow_Menu_Stats_Constructed
        {
            get
            {
                return ResourceManager.GetString("Menu_Stats_Constructed", resourceCulture);
            }
        }
    }
}