name: Main

on:
  push:
    branches:
      - '**'

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Run Bootstrap
        run: ./bootstrap.ps1

      - name: Build (Release)
        run: msbuild "./Hearthstone Deck Tracker.sln" /p:Configuration=Release /p:Platform="x64"

      - name: Setup VSTest
        uses: Malcolmnixon/Setup-VSTest@v4

      - name: Test
        run: |
          vstest.console "HearthWatcher.Test\bin\x64\Release\HearthWatcher.Test.dll"
          $exit1 = $LASTEXITCODE
          vstest.console "HDTTests\bin\x64\Release\HDTTests.dll"
          $exit2 = $LASTEXITCODE
          if ($exit1 -ne 0 -or $exit2 -ne 0) { exit 1 }

      - name: Build (Squirrel)
        run: msbuild "./Hearthstone Deck Tracker.sln" /p:Configuration=Squirrel /p:Platform="x64"
